package com.jbit.dao;

import com.jbit.entity.NewsComment;

public interface NewsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    int deleteByNewsId(Long newsis);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated
     */
    int insert(NewsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated
     */
    int insertSelective(NewsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated
     */
    NewsComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NewsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NewsComment record);
}